### ISSUE TITLE
Add Panel LLamaIndex Chat Pack example

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz-topics/panel-chat-examples#107]
The code can be found here https://github.com/run-llama/llama-hub/pull/703

![PanelChatPack](https://github.com/holoviz-topics/panel-chat-examples/assets/42288570/57cbee98-ba5a-4630-a782-8ef9c9b10696)

We could either add the app as an example with code or have an *awesome chat examples*  section linking to llama hub for this one, the blogposts by Andrew and Sophia, The videos about autogen usage etc.

Let me know what you think @ahuang11 ?

**Comment by ahuang11** [comment]
Wait where is the code?

**Comment by ahuang11** [comment]
I think we can have references.

**Comment by ahuang11** [comment]
Closed by https://github.com/holoviz-topics/panel-chat-examples/pull/109
