### ISSUE TITLE
Roadmap in the near future

### ISSUE THREAD

**Issue by ahuang11** [holoviz-topics/panel-chat-examples#131]
TODO after Panel 1.4.0:

1. Replace Ctransformers with LlamaCpp
2. Replace send() with `help`
3. Add `instructor` streaming example
4. Fix tests
5. Add multi modal example

**Comment by MarcSkovMadsen** [comment]
What would be really nice to know is what would be helpful to existing and potential users. How can we figure that out?

- Should we spend time on updating langchain examples to latest apis?
- Should we spend time on adding more examples and frameworks?
- Should we spend time on improving existing examples?
- or ?

**Comment by ahuang11** [comment]
I was thinking maybe more complex examples; the Chat with GitHub was a good one.
