### ISSUE TITLE
Produce Assets

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz-topics/panel-chat-examples#38]
We should produce assets like thumbnails and gifs. I believe they should be stored in HoloViz CDN instead of in repository. At least the gifs should.

For now we can store them in this issue.

**Comment by MarcSkovMadsen** [comment]
https://github.com/holoviz-topics/panel-chat-examples/assets/42288570/1b799b07-dc27-4848-8598-0b5c609c337f

![echo](https://github.com/holoviz-topics/panel-chat-examples/assets/42288570/2b650eb0-77e4-4060-8715-c3ad5bf65394)

## Replicate

```javascript
let w = window.open(window.location, "dev resize", "resizable");
w.resizeTo(1600, 900);
```

```javascript
w.parent.document.body.style.zoom = 2;
```

**Comment by ahuang11** [comment]
The videos are great!
