### ISSUE TITLE
Improve user experience

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz-topics/panel-chat-examples#46]
Trying to make videos out of the examples I've noticed some things that could make the examples more useful

- [ ] Better file names. The current are focused on technology over use case. For example change `chrome_pdf_qa.py` to `chat_with_pdf.py`.
- [ ] Better code. As these examples will be reference examples for users and copied around, we should try to implement them in the best practice possible. For example breaking down long functions into smaller. Making the apps fast etc. For example the `chrome_pdf_qa.py` could be improved
- [ ] Use the `EnvironmentWidget` to get `OPENAI_API_KEY` etc.
- [ ] Better UX. For example make sure that users cannot `send` etc. before the keys and assets (like pdfs) have been provided.

I will give it my take in https://github.com/holoviz-topics/panel-chat-examples/pull/41.

**Comment by ahuang11** [comment]
I can rename all the files appropriately, but I'm afraid once I do, it'll cause your PRs to have a lot of merge conflicts. I'm thinking of merging your PR first if you think it's mostly ready?
