### ISSUE TITLE
Separate default and dev dependencies

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz-topics/panel-chat-examples#48]
Currently there are lots of `dev` dependencies in the `default` dependencies. The consequence is that it takes a very long time for `hatch` to initialize the `default` environment. For users just want to play around with the examples this is not a great experience.

The solution would be to create a dedicated `dev` environment with `dev` dependencies.

![image](https://github.com/holoviz-topics/panel-chat-examples/assets/42288570/fdca290e-f3ad-4b1d-a9c8-d5c4bc91185d)

**Comment by ahuang11** [comment]
No longer use `hatch` for users; replaced with `pip install .`
