### ISSUE TITLE
openai hvplot example cannot handle anything but small dataframes

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz-topics/panel-chat-examples#51]
If I use for example https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv I get

![image](https://github.com/holoviz-topics/panel-chat-examples/assets/42288570/60217e86-a95e-40ad-a79d-5be65b421348)

An extra issue is that the full csv file is inserted in the chat directly

![image](https://github.com/holoviz-topics/panel-chat-examples/assets/42288570/e6172455-0c89-4962-a25f-b2b2ed054ded)

A much better user experience would be that only a part (`.head`, `.describe`) was inserted. Or that some card or modal was used such that the user could optionally explore the dataframe.

**Comment by ahuang11** [comment]
I think you're supposed to use upload instead of pasting

If you upload the CSV, it does not hit the limit.
<img width="1537" alt="image" src="https://github.com/holoviz-topics/panel-chat-examples/assets/15331990/0cf976a1-7212-42dd-9c86-2f77fbc79149">
