### ISSUE TITLE
Menu not sorted

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz-topics/panel-chat-examples#55]
I was wondering about the organisation of the new menu. What is the sort order and where does it come from?

My initial thought was that it should be sorted automatically. That would be helpful. Especially as it grows.

![image](https://github.com/holoviz-topics/panel-chat-examples/assets/42288570/f5852138-703f-4ac6-969c-c69b1d7fda1d)

**Comment by MarcSkovMadsen** [comment]
I can see its defined here https://github.com/holoviz-topics/panel-chat-examples/blob/main/mkdocs.yml. Is the order on purpose @ahuang11 ?

**Comment by ahuang11** [comment]
It's sorted by my own bias, but yes perhaps alphabetically.

**Comment by MarcSkovMadsen** [comment]
I prefer basics at top and the alphabetically. But its my preference 🙂
