### ISSUE TITLE
Fully Automate Video Creation

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz-topics/panel-chat-examples#58]
Right now the videos created automatically by Playwright are not fully ready for usage because

- They are `.webm` files not supported by iphone. They must be converted to `.mp4`.
- The videos are empty initially for 1-4 seconds. The must be trimmed. That could be automated.
- Sometimes the icons etc. are not loaded initially. That could be fixed.

It would probably also be nice (for social media) if the videos started with a *panel-chat-examples* logo, text or similar. Maybe we could even add some nice audio.

Would be very useful to fully automate this. Would probably have to use [ffmpeg](https://ffmpeg.org/) and python. I It might also be helpful to get Playwright to output to one folder instead of subfolders for each file. See https://playwright.dev/python/docs/videos.

**Comment by ahuang11** [comment]
Done here.
https://github.com/holoviz-topics/panel-chat-examples/pull/64
