### ISSUE TITLE
Get the governance in order

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz-topics/panel-chat-examples#6]
I believe this repository has the potential to become useful to lots of AI Chat interested people. And it could develop rapidly if the processes for accepting contributions are in place.

I would suggest

- [x] Moving this repository to the `holoviz-topics` organisation on Github
- [x] Inviting more core contributors. For example me, Phillip, https://github.com/pierrotsmnrd and https://github.com/pmeier
- [x] Announcing we are looking for core contributors. For example on Discourse: https://discourse.holoviz.org/t/help-us-make-the-next-generation-v-1-3-chat-experience-awesome/6195

**Comment by ahuang11** [comment]
Just transferred to https://github.com/holoviz/panel-chat-examples.

I think I need someone to give me admin rights now to add others.
